/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SocialMedia } from "./SocialMedia";
export * as factories from "./factories";
export { SocialMedia__factory } from "./factories/SocialMedia__factory";
